### ISSUE TITLE
Upload Bug: Fore (EP) by Hungry Jack

### ISSUE THREAD

**Issue by TheJollyLaMa** [TheJollyLaMa/JollyJukeBox#1]
Album uploaded but track list does not show ...

Click on Play Song and get stuck in a prompt loop that reads:
"No tracks available to play."

Here's a screen shot with the console logs from devtools:

![Screenshot 2024-12-17 at 4 54 15 PM](https://github.com/user-attachments/assets/8d6a8311-4647-40a3-8c0e-7a8b07526b68)

**Comment by bobdub** [comment]
I have a suspicion that it is that I uploaded a file format that is not supported onto the ipfs. Could taht be a thing?

**Comment by TheJollyLaMa** [comment]
yes! 🐞

I might just have to add it to the acceptable files whitelist. let us know what it was 🙏

**Comment by bobdub** [comment]
Its .wma 💚 thank you

**Comment by TheJollyLaMa** [comment]
⚸ ✅
added the '.wma' file type - to 3 different sections - in three different ways 😅
#pilotPlAiyngWithFire

Files load in LCd

for V1.3 another coder and I will be meticulously shaving away the redundancies and long-form solutions used to get the base case scenarios hashed out for initial takeoff ... 


relevant lines:

setupUi.js
UpdateRightLCD()
        const validAudioExtensions = [".mp3", ".wav", ".m4a", ".mp4", ".aac", ".mov", ".wma", ".mkv"];

playback.js
playSong()
        if (fileExtension === "mp4" || fileExtension === "mov" || fileExtension === "wma" || fileExtension === "mkv") { ...

playAlbum()
        if (["mp4", "mkv", "mov", "wma"].includes(fileExtension)) { ...


obviously, we will only need one global whitelist. just caught neo jumping rooms again ;)



🚨After doing all that, it turns out wma's do not play in html5 tags anyway. And since we do not have control over what file formats someone is putting in an "album" in their directory on ipfs, this is still a bug worth discussing. I'm going to remove file support for it. For now, jukeboxers, i will have to suggest mp3 and mp4 🚨
